### ISSUE TITLE
DR-DOS 7.07 and WinGlue/WinBolt binaries, source?

### ISSUE THREAD

**Issue by Torinde** [ecm-pushbx/8086tiny#3]
@ecm-pushbx , first thank you and congratulations on the work you do with DOS!

I was happy to see an [updated EDR-DOS 7.01.08 WIP](https://www.bttr-software.de/forum/mix_entry.php?id=20457) and maintained at [your site](https://hg.pushbx.org/ecm/edrdos).

Did you consider creating a Github repository? I think that will make it easy for outside contributors to provide PRs/code, to open Issues, Discussions, etc.

Now that [the license](https://hg.pushbx.org/ecm/edrdos/rev/d4aed5f1b3e6) is [opened](https://hg.pushbx.org/ecm/edrdos/rev/8d01d7fe3cc1) - it would be great if the EDR-DOS branch gets reunited with [DR-DOS 7.07](https://www.hpmuseum.org/forum/thread-8774.html).

Matthias Paul [once wrote](https://msfn.org/board/topic/109018-windows-98-in-dr-dos/?do=findComment&comment=721209):
> I still have not completely lost hope, that at some fine day in the future the current owner of the DR-DOS assets may decide that its commercial life is finally over and that it is due to open source the system. This would make it possible to reunificate the different code branches to create the most advanced DR-DOS ever for all its fans. Well, well... ;-)

So, if he [gets contacted](https://www.bttr-software.de/forum/forum_entry.php?id=16791) (e.g. via [his Wikipedia talk page](https://en.wikipedia.org/wiki/User_talk:Matthiaspaul#Dr-dos_another_life_questions)) in these improved license circumstances, maybe he can help with:
- DR-DOS 7.07 (Kernel and drive tools?) - binary/source?
- [WinGlue/WinBolt](https://msfn.org/board/topic/109018-windows-98-in-dr-dos/?do=findComment&comment=721209) (ability to run Win9x) 
-- binary/source?
-- is combined BIOS+BDOS file mandatory? Or separate files IBMBIO.COM, IBMDOS.COM, MSDOS.SYS (settings text file), IO.SYS (if such kind of placeholder/redirect is needed) can exist at the same time?	
-- can DR-DOS 7.07 boot from Win9x/Me boot sectors? Does DR-DOS 7.07 include all functionality from DR-DOS 7.06?	
-- boot logo, etc. Win9x [settings in MSDOS.SYS](https://www.mdgx.com/msdos.htm)/WINBOOT.INI - any issues with those?
- optionally loadable multi-user security extension - (World/Group/Owner) access permission system - DR DOS "Panther" BETA 1 - birnary/source for that?
- DR-DOS 7.03 source (Kernel or full software package)?

Did you ask Bryan Sparks (the DRDOS owner) if he can help with any of these?
Also, what about:
- DR-DOS 8.0/8.1 - are there any Kernel/IBMBIO/IBMDOS/COMMAND.COM changes in comparison with 7.01.06 and 7.03? FAT32 DELWATCH and SHARE, but those are external files?	
- RxDOS - are there	any changes not yet implemented in the EDR branch? 
- What about functionalities from lDOS not yet implemented in the EDR branch? What is lDOS, actually?
- The last [post by Udo Kuhnt in his forum](http://www.drdosprojects.de/forum/drp_forum/posts/10868.html), 2012-Feb-02 is mentioned [here](https://pmwiki.xaver.me/drdoswiki/index.php?n=Main.HistoryOfDRDOS), but link is broken and I can't find an archive of it. Any clues on that?

PS. Regarding version number - to avoid past confusion cases - would be nice if:
- 6.5, 7.5, 8.5 are [reserved for use in emulators](https://github.com/joncampbell123/dosbox-x/issues/4345#issuecomment-1602085897) - by analogy with NTVDM
- 7.01.08 WIP is kept as "work in progress" and version is not increased to 7.01.09
- 7.08 and 7.09 are reserved for IBMBIO/IBMDOS/COMMAND combination that provides all functionality of EDR-DOS 7.01.08 and DR-DOS 7.07
- 7.1 is reserved for IBMBIO/IBMDOS/COMMAND combination that provides all functionality of MS-DOS 7.1, PC DOS 7.1, DR-DOS 7.07, EDR-DOS 7.01.08
- 8.2 is reserved for IBMBIO/IBMDOS/COMMAND combination that provides all functionality of MS-DOS 8.0, PC DOS 7.1, DR-DOS 7.07, EDR-DOS 7.01.08, DR-DOS 8.0, DR-DOS 8.1, RxDOS 7.2x
- 8.3 and up are reserved for UEFI versions or at least used with restrained, e.g. incremental changes to get increase only in the x.xx.rr revision rather than the minor/major version number.
- 9.0 gets reserved for future substantial change.

PS. I couldn't find more on-topic repository for this comment. One possibility is https://github.com/the-grue/OpenDOS, but I'm not sure if it's active, @the-grue?

**Comment by ecm-pushbx** [comment]
> PS. I couldn't find more on-topic repository for this comment. One possibility is https://github.com/the-grue/OpenDOS, but I'm not sure if it's active, @the-grue?

Please re-post this to our forum, which you already seem to know considering you linked to it. It wouldn't be off-topic there as it is for this repo. (I did not set up any issue tracker related to my hg repos yet. I do not mirror hg repos to git generally because I am less proficient in git.)

If you do not have an account yet, do as [the pinned post says](http://www.bttr-software.de/forum/forum_entry.php?id=1) and drop us a message to indicate what email and what username you'd like to register for the forum:

> 1) To get write access to the forum, [drop us a short message](http://www.bttr-software.de/forum/contact.php). (Please include the username you'd like us to register!)

(I am one of the admins of DOS Ain't Dead so I can create an account if you ask for it.)

**Comment by ecm-pushbx** [comment]
PS I'd suggest a new thread for this post, not to append it to the existing EDR-DOS development thread, as it covers a rather broader set of topics.

**Comment by the-grue** [comment]
I'm still around and willing to update my repo.  I initially created it as it seemed all this good work was going to get lost to the ages, which is why it is a bit stuck in the past.  I think I mined all this stuff out of Wayback machine.

If it is being actively worked elsewhere, I'd be happy to pull in related files for folks to work with.

**Comment by ecm-pushbx** [comment]
@Torinde Do you still want a reply to your questions? I'd be happy to answer in a place that this isn't off-topic.

**Comment by Torinde** [comment]
Yes, I want a reply, but I don't have account at your forums yet. 

Let's continue the discussion at the-grue/OpenDOS/issues/2 (or a new issue in that repository), it'll be on-topic there I think.

**Comment by ecm-pushbx** [comment]
Why not make an account?

**Comment by the-grue** [comment]
I've created a clone of the Mercurial repo here:

https://github.com/the-grue/edrdos

README points back to the original repo and asks that issues/changes/pull requests go to the original author and their repo.

For discussion, feel free to use the Discussions section of that repo.

I'll try to keep my clone in sync as best I can.  Please do not open issues on the OpenDOS repo.  That's really a point-in-time artifact.

Enjoy!

**Comment by Torinde** [comment]
> Do you still want a reply to your questions? I'd be happy to answer in a place that this isn't off-topic.

@ecm-pushbx, questions from above are posted at [the forum](https://www.bttr-software.de/forum/mix_entry.php?id=20457).

**Comment by ecm-pushbx** [comment]
> > Do you still want a reply to your questions? I'd be happy to answer in a place that this isn't off-topic.
> 
> @ecm-pushbx, questions from above are posted at [the forum](https://www.bttr-software.de/forum/mix_entry.php?id=20457).

I have replied now. I wasn't at home for a few days hence only today.

**Comment by Torinde** [comment]
It seems neither binaries nor source is available currently.
